"""Generate offline search readings (does not change audio defaults).

python3 tools/make_search_readings.py Unihan.zip unicode-license.txt
Source: https://www.unicode.org/Public/17.0.0/ucd/Unihan.zip
License: https://www.unicode.org/license.txt
"""
import collections
import pathlib
import re
import sys
import unicodedata
import zipfile

groups = collections.defaultdict(set)
with zipfile.ZipFile(sys.argv[1]) as source:
    raw = source.read('Unihan_Readings.txt').decode('utf-8')
assert '# Unicode Version 17.0.0' in raw
for line in raw.splitlines():
    if not line.startswith('U+'):
        continue
    code, field, value = line.split('\t', 2)
    if field not in ('kMandarin', 'kXHC1983', 'kHanyuPinyin'):
        continue
    for part in value.split():
        for reading in part.split(':')[-1].split(','):
            tone = '5'
            letters = ''
            for char in unicodedata.normalize('NFD', reading.lower()):
                if char in '\u0304\u0301\u030c\u0300':
                    tone = str('\u0304\u0301\u030c\u0300'.index(char) + 1)
                elif char == '\u0308' and letters.endswith('u'):
                    letters = letters[:-1] + 'v'
                elif not unicodedata.combining(char):
                    letters += char
            if re.fullmatch('[a-z]+', letters):
                groups[letters + tone].add(chr(int(code[2:], 16)))
license_text = pathlib.Path(sys.argv[2]).read_text().strip()
rows = '\n'.join(f'{key}:{"".join(sorted(chars))}' for key, chars in sorted(groups.items()))
out = pathlib.Path(__file__).resolve().parents[1] / 'js/search-readings.js'
out.write_text('/*\n' + license_text + '\n*/\n'
               '// Unihan 17.0.0 kMandarin / kXHC1983 / kHanyuPinyin.\n'
               '// Generated by tools/make_search_readings.py; search only, not speech.\n'
               'const RAW = `' + rows + '`;\n'
               'let index;\n'
               'export function searchReadings(ch) {\n'
               '  if (!index) {\n'
               '    index = new Map();\n'
               '    for (const row of RAW.split("\\n")) {\n'
               '      const [syllable, chars] = row.split(":");\n'
               '      for (const char of chars) {\n'
               '        if (!index.has(char)) index.set(char, []);\n'
               '        index.get(char).push(syllable);\n'
               '      }\n'
               '    }\n'
               '  }\n'
               '  return index.get(ch) || [];\n'
               '}\n')
print(f'{out.name}: {len(groups)} syllables, {out.stat().st_size} bytes')
