// 固定版本離線打包：npm ci 後執行，不需要 CDN 或執行期下載字典。
import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'node_modules/opencc-js');
const version = JSON.parse(readFileSync(join(source, 'package.json'), 'utf8')).version;
const dest = join(root, 'js/vendor');
mkdirSync(dest, { recursive: true });
writeFileSync(join(dest, 'opencc.js'), `// Vendored opencc-js ${version}; generated by tools/vendor-opencc.mjs.\n`
  + readFileSync(join(source, 'dist/esm/full.js'), 'utf8'));
for (const [src, out] of [['LICENSE', 'opencc-LICENSE.txt'], ['LICENSES/Apache-2.0.txt', 'opencc-data-LICENSE.txt'],
  ['THIRD_PARTY_LICENSES.md', 'opencc-THIRD-PARTY.md']]) cpSync(join(source, src), join(dest, out));
console.log(`opencc-js ${version} 已打包至 js/vendor/`);
